config/routes.rb
Tracker::Application.routes.draw do

  root :to => redirect('/projects')

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :projects, :only => [:index, :show]

end

app/models/project.rb
class Project < TrackerResource

  self.site = TrackerApi::API_BASE_PATH

  def stories
    @stories ||= Story.filter_stories(Story.find(:all, params: { project_id: self.id }))
  end

  def iterations
    @iterations ||= Iteration.find(:all, params: { project_id: self.id })
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :init_api_token
  before_filter :init_project_and_date_range, :only => :show

  def index
    @projects = Project.all
  end

  def show
    stories = @project.stories
    iterations = @project.iterations

    chart_presenter = ChartPresenter.new(iterations, stories, @start_date, @end_date)
    @active_iterations = chart_presenter.active_iterations

    @velocity_range_chart = chart_presenter.whole_project_velocity_chart()
    @velocity_range_chart.description = ""

    @charts = []
    @charts << chart_presenter.accepted_story_types_chart

    # Chart 1: Velocity
    @charts << chart_presenter.date_range_velocity_chart

    # Chart 2:  When are features discovered?
    @charts << chart_presenter.discovery_and_acceptance_chart(@story_filter)

    # Chart 3: How long did it take for features to be accepted in each week?
    @charts << chart_presenter.acceptance_days_by_iteration_chart(@story_filter)

    # Chart 4: What is the distribution of time to acceptance for features?
    @charts << chart_presenter.acceptance_by_days_chart(@story_filter)
  end

  private

  def init_api_token
    tracker_session = session[TrackerApi::API_TOKEN_KEY]
    TrackerResource.init_session(tracker_session.api_token, tracker_session.session_key)
  end

  def init_project_and_date_range
    @project  = Project.find(params[:id].to_i)

    @start_date = Date.parse(params[:start_date]) unless params[:start_date].blank?
    @end_date = Date.parse(params[:end_date]) unless params[:end_date].blank?

    @story_filter = []
    Story::ALL_STORY_TYPES.each do |type|
      if not params[type].blank?
        @story_filter << type
      end
    end

    @story_filter = ChartPresenter::DEFAULT_STORY_TYPES if @story_filter.empty?
    @story_filter.each do |type|
      params[type] = '1'
    end
  end
end

app/views/projects/index.html.haml
%h2 Projects
%ul
  - @projects.each do |project|
    %li= link_to project.name, project_path(project.id)

app/views/projects/show.html.haml
%h2 Projects - #{@project.name}

%div
  = render :partial => 'shared/chart', locals: {chart: @velocity_range_chart, chart_id: "velocity-range-chart"}
  %div#iteration-range

= form_for :project, url: project_path(@project.id), method: :get do |form|
  %fieldset
    %legend Select dates
    = text_field_tag :start_date, params[:start_date], :placeholder => "Start YYYY/MM/DD"
    = text_field_tag :end_date, params[:end_date], :placeholder => "End YYYY/MM/DD"
  %fieldset
    %legend Select story types
    - Story::ALL_STORY_TYPES.each do |story_type|
      %label #{story_type.pluralize.titleize} #{check_box_tag story_type, '1', params[story_type], class: 'story_type_filter_cbx'}

  %fieldset.buttons
    = form.submit "Refresh Charts", :class => "btn"

- iterations = [""]
- iterations += @active_iterations.map{|it| it.start.strftime('%Y/%m/%d')} unless @active_iterations.nil?

:javascript
  $(function() {
    TrackerStats.set_property("iterations", #{iterations.to_json})
    TrackerStats.add_datepicker('#start_date');
    TrackerStats.add_datepicker('#end_date');
    TrackerStats.setup_iterations_slider('#iteration-range', '#start_date', '#end_date');
    $('div.tooltip_hotspot').tooltip({relative: true}).dynamic();
  });

- @charts.each_with_index do |chart, idx|
  = render :partial => 'shared/chart', locals: {chart: chart, chart_id: "chart_#{idx}"}